### ISSUE TITLE
Missing DSO : Installation of stable-4.2 

### ISSUE THREAD

**Issue by wenhuizhang** [mirage/xen#1]
Hi, I am installing stable-4.2 branch on Ubuntu 14.04, and it seems like some DSO is missing and no LIBS or FLAGS was found in the main Makefile, is it mentioned in some sub-folders please?

Error Trace:

```
/usr/bin/ld: vl.o: undefined reference to symbol 'timer_settime@@GLIBC_2.3.3'
//lib/x86_64-linux-gnu/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[4]: *** [qemu-dm] Error 1
make[4]: Leaving directory `/home/wenhui/ClickOS/xen/tools/qemu-xen-traditional-dir-remote/i386-dm'
make[3]: *** [subdir-i386-dm] Error 2
make[3]: Leaving directory `/home/wenhui/ClickOS/xen/tools/qemu-xen-traditional-dir-remote'
make[2]: *** [subdir-install-qemu-xen-traditional-dir] Error 2
make[2]: Leaving directory `/home/wenhui/ClickOS/xen/tools'
make[1]: *** [subdirs-install] Error 2
make[1]: Leaving directory `/home/wenhui/ClickOS/xen/tools'
make: *** [install-tools] Error 2
```

**Comment by samoht** [comment]
probably wrong issue tracker? This fork is only an unofficial mirror of xenbits.xen.org/xen.git 

@avsm we should disable the issue tracker I think

**Comment by wenhuizhang** [comment]
Do they have issue trackers on github? The link  xenbits.xen.org/xen.git could not be accessed. Thanks.

**Comment by wenhuizhang** [comment]
The issue tracker could be disabled from settings->feature->issues  @samoht @avsm

**Comment by samoht** [comment]
> http://wiki.xenproject.org/wiki/Reporting_Bugs_against_Xen_Project
> The primary location for reporting bugs against the hypervisor and associated bundled tools (e.g. against xen.git, xen-unstable.hg or xen-X.Y-testing.hg) is by posting to the xen-devel mailing list (list info). Please tag your subject line with a '[BUG]' prefix. Note that you do not need to be subscribed to the list to post (although non-subscribers are moderated this usually happens pretty quickly) and that list policy is to CC people so you shouldn't miss any replies

**Comment by wenhuizhang** [comment]
Thanks so much @samoht , just send out. I am closing this issue.
